---
- name: main entrypoint
  hosts: "localhost"
  gather_facts: false
  vars:
    _allowed_envs:
      - build
      - qa
      - prd
    #_foo: "{{ (ansible_os_family == 'Debian') | ternary('Mr','Ms') }}"
    tagsa:
      - key: Application
        value: payment
      - key: Environment
        value: dev

  roles:
    - {role: "{{ role }}"}