---

- name: git clone from repo
  git:
    repo: 'https://github.com/cjaiwenwen/environment.git'
    dest: "{{ playbook_dir }}"

- name: load the variable
  include_vars:
    file: "{{ playbook_dir }}/env.yaml"